### ISSUE TITLE
req.body reads from input's name attribute

### ISSUE THREAD

**Issue by barrycumbie** [Bjacks01/umbrella-dev-Real#5]
https://github.com/Bjacks01/umbrella-dev-Real/blob/af686a19dc56bfefe805910d8825eaf2d634dc1a/views/index.ejs#L53C15-L59C21

Your code isn't passing along the values of the `<inputs>` as it is. They need the `name=` attribute (which is common to name the same as the `id=` attribute

example: 

```diff
-<input id="updateName" class="topInput" type="text" placeholder="Name">
+<input id="updateName" name="updateName" class="topInput" type="text" placeholder="Name">
 <br>
- <input id="updatePosition" type="text" placeholder="Position">
+<input id="updatePosition" name="updatePosition" type="text" placeholder="Position">
              </div>
...
```

**Comment by Bjacks01** [comment]
Thanks for the fix, knew it was gonna be something simple that I didn't think of all weekend.
